# Generated by Django 5.2 on 2026-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='university',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('u_code', models.CharField(max_length=20, unique=True)),
                ('u_city', models.CharField(max_length=100)),
                ('u_state', models.CharField(max_length=100)),
                ('u_country', models.CharField(max_length=100)),
            ],
        ),
    ]
