# Generated by Django 5.2 on 2026-03-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='u_id',
        ),
        migrations.AddField(
            model_name='university',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
