# Generated by Django 5.2 on 2026-03-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0002_remove_university_u_id_university_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='u_country',
        ),
        migrations.AddField(
            model_name='university',
            name='u_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='u_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
